import Head from "next/head"
import Image from "next/image"
import { Inter } from "@next/font/google"
import { useTheme } from "next-themes"

export default function Home() {
  const { theme, setTheme } = useTheme()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-zinc-800 dark:text-blue-500">
          Next.js + Tailwind CSS
        </h1>
        <button onClick={() => setTheme(theme === "dark" ? "light" : "dark")}>
          Toggle {theme === "dark" ? "Light" : "Dark"}
        </button>

        <div className="flex flex-col items-center justify-center min-h-screen py-2">
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          <p className="mt-3 text-2xl font-extrabold text-center text-gray-900">
            Welcome to{" "}
            <a
              className="text-blue-600"
              href="https://nextjs.org"
              target="_blank"
              rel="noopener noreferrer">
              Next.js!
            </a>
          </p>
        </div>
      </main>
    </>
  )
}
