import Head from "next/head"
import Link from "next/link"

export default function Home() {
  return (
    <>
      <Head>
        <title>Ybc - Quiz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center items-center h-screen flex-col">
        <h1 className="mb-8 sm:mb-10 xl:mb-20 font-maxbold text-4xl sm:text-6xl xl:text-7xl underline decoration-sky-500 decoration-6 ">
          Hoşgeldiniz...
        </h1>
        <Link
          href={"/quiz"}
          className="border-4 border-violet-700 px-8 py-4 rounded-lg shadow-lg shadow-violet-300/50 font-semibold text-xl hover:scale-110 duration-200 hover:shadow-xl hover:shadow-violet-400/50 bg-violet-500  text-violet-800 ">
          Free Quiz
        </Link>
      </main>
    </>
  )
}
