import Head from "next/head"
import { useEffect } from "react"
import { uid } from "uid"
import { ref, set } from "firebase/database"
import { db } from "@/libs/firebase"

export default function Home() {
  const bcrypt = require("bcryptjs")
  function writeUserData(userId, name, email, imageUrl) {
    set(ref(db, "users/" + userId), {
      username: name,
      email: email,
      profile_picture: imageUrl,
    })
  }

  const handleSubmit = (e) => {
    e.preventDefault()
    const name = e.target.name.value
    const email = e.target.email.value
    const imageUrl = e.target.imageUrl.value
    const userId = uid()
    writeUserData(userId, name, email, imageUrl)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Home</h1>

        <form onSubmit={handleSubmit}>
          <div>
            <label htmlFor="name">Name</label>
            <input type="text" name="name" id="name" />
          </div>
          <div>
            <label htmlFor="email">Email</label>
            <input type="email" name="email" id="email" />
          </div>
          <div>
            <label htmlFor="imageUrl">Image URL</label>
            <input type="text" name="imageUrl" id="imageUrl" />
          </div>
          <button type="submit">Submit</button>
        </form>
      </main>
    </>
  )
}
