import React from "react"
import Head from "next/head"
import { tr, en, lang } from "@/lang/langT"
import { useRouter } from "next/router"
import { db } from "@/libs/firebase"
import { ref, onValue, push } from "firebase/database"
import { uid } from "uid"
import Swal from "sweetalert2"
import { IoIosWarning } from "react-icons/io"

const QuizCreate = () => {
  const [questions, setQuestions] = React.useState([])
  let selectedQuestions = []
  const router = useRouter()
  const { locale } = router
  const t = lang(locale)

  const changeLanguage = (e) => {
    const locale = e.target.value
    router.push(router.pathname, router.asPath, { locale })
  }

  const urlCopy = (text) => {
    navigator.clipboard.writeText(text)
    Swal.fire({
      title: "Success!",
      text: "Link copied to clipboard",
      icon: "success",
      showConfirmButton: false,
      timer: 1500,
    })
  }

  return (
    <>
      <Head>
        <title>Quiz Create</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto pt-28 px-5">
        <div className="grid grid-cols-12 gap-y-7">
          <div className="col-span-3 px-4 py-4 relative hidden lg:flex">
            <div className="bg-gray-600 h-40 sticky top-12 w-full flex justify-center items-center text-white  ">
              Reklamlar
            </div>
          </div>
          <div className="col-span-12 lg:col-span-6 px-3 sm:px-6 mb-10">
            <section className="">
              <h1 className="mb-10 font-maxbold text-4xl sm:text-5xl text-center underline underline-offset-4 decoration-sky-500 decoration-4 ">
                Quiz Oluşturuldu...
              </h1>
              <p className="mb-10 font-medium text-lg text-center text-gray-500 ">
                Quiz başarıyla oluşturuldu. Quizinizi paylaşmak için aşağıdaki
                bağlantıyı kopyalayın.
              </p>
              <p className="mb-10 font-medium text-lg text-center text-gray-400 bg-gray-200 border-2 border-gray-500/60 shadow-md rounded-sm py-2 overflow-auto px-8 ">
                {`${process.env.NEXT_PUBLIC_APP_URL}/quizsolve/${router.query.id}`}
              </p>

              <div className="flex justify-center">
                <button
                  className="px-4 py-2 border-[3px] border-blue-800 bg-blue-600 text-blue-800 shadow-lg shadow-blue-600/50 hover:shadow-xl hover:shadow-blue-600/50 duration-300 hover:scale-110 rounded-sm font-semibold text-xl"
                  onClick={() =>
                    urlCopy(
                      `${process.env.NEXT_PUBLIC_APP_URL}/quizsolve/${router.query.id}`
                    )
                  }>
                  Kopyala
                </button>
              </div>

              <div className="flex flex-col justify-center items-start mt-10">
                <p className="mb-10 font-medium text-lg text-center text-gray-500 flex flex-col ">
                  <span className="bg-yellow-300 text-yellow-600 px-4 py-2 rounded-sm flex  justify-between mb-2 items-center font-semibold">
                    <IoIosWarning fontSize={26} /> Aşağıdaki Quiz Id'sini
                    saklayınız.
                    <IoIosWarning fontSize={26} />
                  </span>
                  <span>
                    Oluşturmuş olduğunuz quiz'e , partnerinizin verdiği
                    cevapları görebilmek için gerekli olacaktır.
                  </span>
                </p>
                <p className="mb-10 w-full font-medium text-lg text-center text-gray-400 bg-gray-200 border-2 border-gray-500/60 shadow-md rounded-sm py-2 px-8 overflow-auto ">
                  {router.query.id}
                </p>
                <div className=" flex justify-center w-full">
                  <button
                    className=" mb-10 inline-block w-auto px-4 py-2 border-[3px] border-blue-800 bg-blue-600 text-blue-800 shadow-lg shadow-blue-600/50 hover:shadow-xl hover:shadow-blue-600/50 duration-300 hover:scale-110 rounded-sm font-semibold text-xl"
                    onClick={() => urlCopy(`${router.query.id}`)}>
                    Kopyala
                  </button>
                </div>
              </div>
            </section>
          </div>
          <div className="col-span-3 px-4 py-4 relative hidden lg:flex">
            <div className="bg-gray-600 h-40 sticky top-12 w-full flex justify-center items-center text-white  ">
              Reklamlar
            </div>
          </div>
        </div>
      </main>
    </>
  )
}

export default QuizCreate
